%
% plot_core_concs_pred(data,core_plot,predN)
% plot_core_concs_pred(data,core_plot,predN,nuclides,nuclide_log,pred_col)
%
% Plots the predicted nuclide concentrations for each core segment over
% plotted measured nuclide concentrations.
%
% data is a required struct containing necessary sample details.
%
% core_plot should contain the handles generated by plot_core_concs.m.
%
% pred_N is a required struct of predicted (summed) nuclide concentrations.
%
% nuclides is a vector of nuclides measured (10, 14, 26).
%
% nuclide_log is a logical of samples for each nuclide (top row is 10Be,
% second row is 14C or 26Al).
%
% pred_col is an optional input to specify the colour used for plotting the
% predicted nuclide concentrations. Default is green.
%
%
%%

function plot_core_concs_pred(data,core_plot,predN,nuclides,nuclide_log,pred_col)

  % Check inputs
  if (nargin < 4 || nargin > 6)
      error('plot_core_concs has wrong number of inputs!');
  end
  if (nargin < 6 || isempty(pred_col))
      pred_col = 'g';
  end
  
  
  axes(core_plot(2));
  
  if any(ismember(nuclides,10))

      logical_10 = nuclide_log(1,:);
      data_N10 = data(logical_10);
      pred_N10 = predN.N10(:,logical_10);
      
      % For each sample
      for a = 1:length(data_N10)
          
          xx = [pred_N10(:,a) pred_N10(:,a)]/1000;
          
          % For each sample depth
          for b = 1:length(data_N10{a}.top_z_cm)
              
              yy = [data_N10{a}.top_z_cm(b) data_N10{a}.bottom_z_cm(b)];
              %plot(xx,yy,'Color',pred_col,'LineWidth',2);
              
              % For each prediction
              for c = 1:length(pred_N10(:,1))
                  this_pred_xx = xx(c,:);
                  % if isempty(findobj('tag',['pred_N10' int2str(a) int2str(b)]))
                  %     plot(this_pred_xx,yy,'Color',pred_col,'tag',['pred_N10' int2str(a) int2str(b)]); hold on;
                  %     set(findobj('tag',['pred_N10' int2str(a) int2str(b)]),'LineWidth',2);
                  % else
                  %     set(findobj('tag',['pred_N10' int2str(a) int2str(b)]),'xdata',this_pred_xx,'ydata',yy);
                  % end
                  tag_str = ['pred_N10_' int2str(a) '_' int2str(b) '_' int2str(c)];
                  % plot(this_pred_xx, yy, 'Color', pred_col, 'tag', tag_str, 'LineWidth', 1.5); hold on;
                  h = findobj(core_plot(2), 'tag', tag_str);
                  if isempty(h)
                      % Plot new prediction line if it doesn't exist
                      plot(this_pred_xx, yy, 'Color', pred_col, 'tag', tag_str, 'LineWidth', 1.5);
                  else
                      % Update existing line
                      set(h, 'XData', this_pred_xx, 'YData', yy);
                  end
              end

          end
      end
      
  end
  
  
  if any(ismember(nuclides,14))
      
      logical_14 = nuclide_log(2,:);
      data_N14 = data(logical_14);
      pred_N14 = predN.N14(:,logical_14);
      
      % For each sample
      for a = 1:length(data_N14)
          
          xx = [pred_N14(:,a) pred_N14(:,a)]/1000;
          
          % For each sample depth
          for b = 1:length(data_N14{a}.top_z_cm)
              
              yy = [data_N14{a}.top_z_cm(b) data_N14{a}.bottom_z_cm(b)];
              %plot(xx,yy,'Color',pred_col,'LineWidth',2);

              % For each prediction
              for c = 1:length(pred_N14(:,1))
                  this_pred_xx = xx(c,:);
                  % if isempty(findobj('tag',['pred_N14' int2str(a) int2str(b)]))
                  %     plot(this_pred_xx,yy,'Color',pred_col,'tag',['pred_N14' int2str(a) int2str(b)]); hold on;
                  %     set(findobj('tag',['pred_N14' int2str(a) int2str(b)]),'LineWidth',2);
                  % else
                  %     set(findobj('tag',['pred_N14' int2str(a) int2str(b)]),'xdata',this_pred_xx,'ydata',yy);
                  % end
                  tag_str = ['pred_N14_' int2str(a) '_' int2str(b) '_' int2str(c)];
                  % plot(this_pred_xx, yy, 'Color', pred_col, 'tag', tag_str, 'LineWidth', 1.5); hold on;
                  h = findobj(core_plot(2), 'tag', tag_str);
                  if isempty(h)
                      % Plot new prediction line if it doesn't exist
                      plot(this_pred_xx, yy, 'Color', pred_col, 'tag', tag_str, 'LineWidth', 1.5);
                  else
                      % Update existing line
                      set(h, 'XData', this_pred_xx, 'YData', yy);
                  end
              end

          end
      end
      
  end

  if any(ismember(nuclides,26))
      
      logical_26 = nuclide_log(3,:);
      data_N26 = data(logical_26);
      pred_N26 = predN.N26(:,logical_26);
      
      % For each sample
      for a = 1:length(data_N26)
          
          xx = [pred_N26(:,a) pred_N26(:,a)]/1000;
          
          % For each sample depth
          for b = 1:length(data_N26{a}.top_z_cm)
              
              yy = [data_N26{a}.top_z_cm(b) data_N26{a}.bottom_z_cm(b)];
              %plot(xx,yy,'Color',pred_col,'LineWidth',2);
              
              % For each prediction
              for c = 1:length(pred_N26(:,1))
                  this_pred_xx = xx(c,:);
                  % if isempty(findobj('tag',['pred_N26' int2str(a) int2str(b)]))
                  %     plot(this_pred_xx,yy,'Color',pred_col,'tag',['pred_N26' int2str(a) int2str(b)]); hold on;
                  %     set(findobj('tag',['pred_N26' int2str(a) int2str(b)]),'LineWidth',2);
                  % else
                  %     set(findobj('tag',['pred_N26' int2str(a) int2str(b)]),'xdata',this_pred_xx,'ydata',yy);
                  % end
                  tag_str = ['pred_N26_' int2str(a) '_' int2str(b) '_' int2str(c)];
                  % plot(this_pred_xx, yy, 'Color', pred_col, 'tag', tag_str, 'LineWidth', 1.5); hold on;
                  h = findobj(core_plot(2), 'tag', tag_str);
                  if isempty(h)
                      % Plot new prediction line if it doesn't exist
                      plot(this_pred_xx, yy, 'Color', pred_col, 'tag', tag_str, 'LineWidth', 1.5);
                  else
                      % Update existing line
                      set(h, 'XData', this_pred_xx, 'YData', yy);
                  end
              end

          end
      end
      
  end

  hold off;
  
end
    